[.text-justify]

== Processing Standards

=== Web Processing Service (WPS)
==== Introduction
==== Background
===== History
===== Versions
===== Implementations

Implementations can be found on the http://www.opengeospatial.org/resource/products/byspec[OGC Compliance Database]. 

===== Endpoints on the NGDI-20-60 OGC API Testbed Platform

The Web Processing Service (WPS) standard has not been integrated into the Testbed platform.

==== Operations
==== Relation to other OGC Standards

- <<OGC API - Processes>>

NOTE:  compile a summary of the major differences between the 2 standards

==== Relation with eCH-0056

The Web Processing Service (WPS) standard is not mentioned in the eCH-0056 document.

==== Proposed modifications to eCH-0056

=== OGC API - Processes
==== Introduction
==== Background
===== History
===== Versions
===== Implementations

Implementations can be found on the http://www.opengeospatial.org/resource/products/byspec[OGC Compliance Database]. 

===== Endpoints on the NGDI-20-60 OGC API Testbed Platform

Examples of implementations can be found on the https://ogc.heig-vd.ch/pygeoapi/processes?f=html[
NGDI-20-60 OGC API Testbed Platform]

NOTE: update the link once the structure of the Testbed Platform adapted.

==== Operations
==== Relation to other OGC Standards

- <<Web Processing Service (WPS)>>

NOTE:  compile a summary of the major differences between the 2 standards

==== Relation with eCH-0056

The OGC API - Processes standard is not mentioned in the eCH-0056 document.

==== Proposed modifications to eCH-0056

- Integrate the OGC API - Processes in the same sections as the WPS standard in the eCH-0056 document  according to its extensions.
- Add a new section to the eCH-0056 document that describes the OGC API - Processes.
- Update the structure of the eCH-0056 document according to the versions and functionalities of the OGC API - Processes.