[.text-justify]
== Visualization Standards

=== 1. Web Map Service (WMS)
==== 1.1 Introduction
==== 1.2 Background
===== 1.2.1 History
===== 1.2.2 Versions
===== 1.2.3 Implementations

Implementations can be found on the http://www.opengeospatial.org/resource/products/byspec[OGC Compliance Database]. 

===== 1.2.4 Endpoints on the NGDI-20-60 OGC API Testbed Platform

The Web Map Service (WMS) standard has not been integrated into the Testbed platform.

==== 1.3 Operations
==== 1.4 Relation to other OGC Standards

- <<2. OGC API Maps>>

NOTE:  compile a summary of the major differences between the 2 standards

==== 1.5 Relation with eCH-0056

The Web Map Service (WMS) standard is currently mentioned in the following sections:

3.4, 5, 3.7, 6.3, 6.6 (`QUAL-02`), 6.7 (`WMS-01`,`WMS-02`,`WMS-03`,`WMS-04`,`WMS-05`,`WMS-06`,`WMS-07`,`WMS-08`,`WMS-09`,`WMS-10`), 6.11, 6.12, appendix B (`Mapping: WMS metadata elements -> GM03`, `Mapping: mandatory GM03 metadata elements -> WMS, WMTS, WFS, WCS et CSW`) & E

of the eCH-0056 document.

==== 1.6 Proposed modifications to eCH-0056

=== 2. OGC API Maps
==== 2.1 Introduction
==== 2.2 Background
===== 2.2.1 History
===== 2.2.2 Versions
===== 2.2.3 Implementations

Implementations can be found on the http://www.opengeospatial.org/resource/products/byspec[OGC Compliance Database]. 

===== 2.2.4 Endpoints on the NGDI-20-60 OGC API Testbed Platform
==== 2.3 Operations
==== 2.4 Relation to other OGC Standards

- <<1. Web Map Service (WMS)>>

NOTE:  compile a summary of the major differences between the 2 standards

==== 2.5 Relation with eCH-0056

The OGC API Maps standard is not mentioned in the eCH-0056 document.

==== 2.6 Proposed modifications to eCH-0056

The OGC API Maps standard has not yet been validated by the OGC. It is therefore difficult to take a position on its integration into the eCH-0056 document.

=== 3. Web Map Tile Service (WMTS)
==== 3.1 Introduction
==== 3.2 Background
===== 3.2.1 History
===== 3.2.2 Versions
===== 3.2.3 Implementations

Implementations can be found on the http://www.opengeospatial.org/resource/products/byspec[OGC Compliance Database]. 

===== 3.2.4 Endpoints on the NGDI-20-60 OGC API Testbed Platform

The Web Map Tile Service (WMTS) standard has not been integrated into the Testbed platform.

==== 3.3 Operations
==== 3.4 Relation to other OGC Standards

- <<4. OGC API Tiles>>

NOTE:  compile a summary of the major differences between the 2 standards

==== 3.5 Relation with eCH-0056

The Web Map Tile Service (WMTS) standard is currently mentioned in the following sections:

2, 3.4, 6.4, 6.8 (`WMTS-01`,`WMTS-02`,`WMTS-03`,`WMTS-04`,`WMTS-05`,`WMTS-06`,`WMTS-07`,`WMTS-08`)
appendix B (`Mapping: WMTS metadata elements -> GM03`, `Mapping: mandatory GM03 metadata elements -> WMS, WMTS, WFS, WCS et CSW`) & E

of the eCH-0056 document.


==== 3.6 Proposed modifications to eCH-0056

=== 4. OGC API Tiles
==== 4.1 Introduction
==== 4.2 Background
===== 4.2.1 History
===== 4.2.2 Versions
===== 4.2.3 Implementations

Implementations can be found on the http://www.opengeospatial.org/resource/products/byspec[OGC Compliance Database]. 

===== 4.2.4 Endpoints on the NGDI-20-60 OGC API Testbed Platform
==== 4.3 Operations
==== 4.4 Relation to other OGC Standards

- <<3. Web Map Tile Service (WMTS)>>

NOTE:  compile a summary of the major differences between the 2 standards

==== 4.5 Relation with eCH-0056

The OGC API Tiles standard is not mentioned in the eCH-0056 document.

==== 4.6 Proposed modifications to eCH-0056

The OGC API Tiles standard has not yet been validated by the OGC. It is therefore difficult to take a position on its integration into the eCH-0056 document.

=== 5. Styled Layer Descriptor (SLD)
==== 5.1 Introduction
==== 5.2 Background
===== 5.2.1 History
===== 5.2.2 Versions
===== 5.2.3 Implementations

Implementations can be found on the http://www.opengeospatial.org/resource/products/byspec[OGC Compliance Database]. 

===== 5.2.4 Endpoints on the NGDI-20-60 OGC API Testbed Platform

==== 5.3 Operations
==== 5.4 Relation to other OGC Standards

- <<7. OGC API Styles>>

NOTE:  compile a summary of the major differences between the 2 standards

==== 5.5 Relation with eCH-0056

The Styled Layer Descriptor (SLD) standard is currently mentioned in the following sections:
6.7 (`WMS-09`), 6.12 (`SLD-01`) & appendix E of the eCH-056 document.

==== 5.6 Proposed modifications to eCH-0056

=== 6. Symbology Encoding (SE)
==== 6.1 Introduction
==== 6.2 Background
===== 6.2.1 History
===== 6.2.2 Versions
===== 6.2.3 Implementations

Implementations can be found on the http://www.opengeospatial.org/resource/products/byspec[OGC Compliance Database]. 

===== 6.2.4 Endpoints on the NGDI-20-60 OGC API Testbed Platform
==== 6.3 Operations
==== 6.4 Relation to other OGC Standards

- <<8. OGC Symbology Conceptual Model: Core Part>>

NOTE:  compile a summary of the major differences between the 2 standards

==== 6.5 Relation with eCH-0056

The Styled Layer Descriptor (SLD) standard is currently mentioned in the sections 6.11 the eCH-056 document.

==== 6.6 Proposed modifications to eCH-0056

=== 7. OGC API Styles
==== 7.1 Introduction
==== 7.2 Background
===== 7.2.1 History
===== 7.2.2 Versions
===== 7.2.3 Implementations

Implementations can be found on the http://www.opengeospatial.org/resource/products/byspec[OGC Compliance Database]. 

===== 7.2.4 Endpoints on the NGDI-20-60 OGC API Testbed Platform
==== 7.3 Operations
==== 7.4 Relation to other OGC Standards

- <<8. OGC Symbology Conceptual Model>>

NOTE:  compile a summary of the major differences between the 2 standards

==== 7.5 Relation with eCH-0056

The OGC API Styles standard is not mentioned in the eCH-0056 document.

==== 7.6 Proposed modifications to eCH-0056

The OGC API Styles standard has not yet been validated by OGC. It is therefore difficult to take a position on its integration into the eCH-0056 document.

=== 8. OGC Symbology Conceptual Model
==== 8.1 Introduction
==== 8.2 Background
===== 8.2.1 History
===== 8.2.2 Versions
===== 8.2.3 Implementations

Implementations can be found on the http://www.opengeospatial.org/resource/products/byspec[OGC Compliance Database]. 

===== 8.2.4 Endpoints on the NGDI-20-60 OGC API Testbed Platform
==== 8.3 Operations
==== 8.4 Relation to other OGC Standards

- <<6. Symbology Encoding (SE)>>

NOTE:  compile a summary of the major differences between the 2 standards

==== 8.5 Relation with eCH-0056

The OGC Symbology Conceptual Model: Core Part standard is not mentioned in the eCH-0056 document.

==== 8.6 Proposed modifications to eCH-0056

- Integrate the OGC Symbology Conceptual Model in the same sections as the Symbology Encoding (SE) standard in the eCH-0056 document  according to its extensions.
- Add a new section to the eCH-0056 document that describes the OGC Symbology Conceptual Model.
- Update the structure of the eCH-0056 document according to the versions and functionalities of the OGC Symbology Conceptual Model.
