// Document settings
[.text-justify]
// Bibtex config: https://github.com/asciidoctor/asciidoctor-bibtex#configuration
:bibtex-file: references.bib
:bibtex-style: apa
:bibtex-format: asciidoc
:bibtex-throw: true

== Introduction

Recently, in 2022, the Open Geospatial Consortium (OGC) and the Open Source Geospatial Foundation (OSGeo) have renewed their Memorandum of Understanding. While the initial agreement dates from 2008, this renewal is especially motivated by the current focus on the OGC APIs and the will to empower developers (even non-geospatial) to leverage location in their development. Indeed, the OGC has initiated the creation of a new generation of standards based on the OpenAPI specifications to facilitate the integration of geospatial data in modern web applications and systems.

Underpinning the OGC Standards Roadmap cite:[ogc-roadmap], the development of all these standards represents a significant number of activities carried out by various OGC working groups, Testbeds and pilots from the OGC Innovation Program cite:[ogc-ip]. Some standards have been approved, many are still under development and it is therefore not always easy to follow their progress. Indeed, while some geodata infrastructures involving national entities as the(e.g. Meteorological Service of Canada cite:[eccc-msc] in Canada) are already deploying this new generation of standards, some initiatives run a phase of experimentation such as for instance the Geonovum OGC API Testbed Platform cite:[apitestbed].

=== Context

In Switzerland the exchange and publication of geographic information is governed by the Federal Act on Geoinformation (GeoIA) cite:[geoia]. The GeoIA is accompanied by two regulations:

* GeoIV/OGeo (Federal Council Ordinance) cite:[ogeo]
* GeoIV/OGeo-swisstopo (Ordinance specific for the Federal Office of Topography swisstopo) cite:[ogeo-swisstopo]

The GeoIV/OGeo contains the fundamental provisions, while the GeoIV/OGeo-swisstopo regulates the technical details, which can be modified by the competent federal office (swisstopo), with the participation of the cantons and after consultation with different partner organisations:

* http://www.ech.ch[eCH], a national association for the establishment of e-government standards
* https://www.sogi.ch[SOGI/OSIG], a national association for geoinformation
* https://www.kgk-cgc.ch[KGK-CGC], an organization of the Swiss Cantons in the field of geoinformation management

The GeoIV/OGeo-swisstopo specifies criteria such as the geodetic reference system, the description language for modeling geospatial data, metadata standards for geoinformation and minimal requirements for geodata.

In its 7th article: ”Minimal requirements for geoservices”, the GeoIV/OGeo-swisstopo refers to the e-Government standard eCH-0056 entitle Application Profile for Geoservices cite:[eCH-0056], which defines the implementation of basic geoservices by means of a set of additional guidelines and recommendations which make the services suitable for practical use. In addition, there are other regulations, such as metadata models cite:[gm03] and protocols for the exchange of base geodata under federal law.

As the eCH-0056 document currently refers to the WxS family of OGC specifications (WMS, WMTS, WFS, WCS, CSW, SE, SLD, SOS), our research aims to assess the maturity and the benefits of the new OGC APIs in the perspective of a revision of its legal framework.

=== Fundamental questions

From a practical perspective we can ask the question how organizations and institutions anticipate to leverage this new generation of standards in order to deploy a geospatial data infrastructure. This issue is at the core of this project that seeks to address it by running an OGC API Testbed platform with a special focus to the Swiss context. This project is embedded in the NGDI Resources program related to the Swiss Geoinformation Strategy cite:[indg] with the purpose to contribute to the upcoming revision of Swiss e-government standards regarding geoinformation such as the eCH-0056 cite:[eCH-0056] standard. This project is about a research carried out by academic partners (HEIG-VD, SUPSI, UNIGE) as well as the Swiss Office for Topography Swisstopo.
