// Document settings
[.text-justify]

== Metadata & Catalogue Services Standards

=== Introduction

This section describes the main standards for accessing metadata through web geoservices.

=== Catalog Services for the web (CSW)

==== Introduction

Catalogue services support the ability to publish and search collections of descriptive information (metadata) for data, services, and related information objects. Metadata in catalogues represent can be queried and presented for evaluation and further processing by both humans and software. Catalogue services are required to support the discovery and binding to registered information resources within an information community.

Source : https://opengeospatial.github.io/e-learning/cat/text/main.html[Open Geospatial Consortium]

==== Background

===== History

The version 2.0.2 was released in 2007 followed by the version 3.0 in 2016 which adds open search support.

===== Versions

http://docs.opengeospatial.org/is/12-168r6/12-168r6.html[Version 3.0 - 12-168r6] is the current latest. It adds open search support.

===== Implementations

Implementations can be found on the http://www.opengeospatial.org/resource/products/byspec[OGC Compliance Database]. 

===== Endpoints on the NGDI-20-60 OGC API Testbed Platform

The Catalogue Services for the Web (CSW) standard has not been integrated into the Testbed platform.

=== Operations, Ressources

.Overview of the CSW operations
[cols="1,1"]
|===
*Operation* | *Description*
| `GetCapabilities` | Returns information about the server instance.
| `DescribeRecord` | Returns the information models used by the server to return the metadata records.
| `GetRecordById` | Retrieves the default representation of catalogue records using an identifier.
| `GetRecords` | Searches for records given a set of criteria.
| `GetDomain (Optional)` | Used to obtain the range of values of a metadata property.
| `Harvest (Optional)` | Create/update metadata by asking the server to `pull` metadata from somewhere.
|===

==== Relation to other OGC Standards

- <<OGC API Records>>
- <<Spatio Temporal Asset Catalog>>


==== Relation with eCH-0056

The CSW standard is currently mentioned in the following sections:

3.4, 6.10 (`CSW-01`, `CSW-02`, `CSW-03`), appendix A, & appendix B

of the eCH-0056 document.

==== Proposed modifications to eCH-0056

Refer to version 3.0 of the specification.

=== OGC API Records

==== Introduction

OGC API - Records is a new OGC API standard that provides a simple and consistent way to publish and access descriptive information about geospatial resources. It is based on the OGC API - Features standard and uses the same core concepts of resources, collections, and items. The OGC API - Records standard defines a core set of functionality that can be extended by additional functionality defined in separate standards.

==== Background

===== History

The OGC API - Records standard is currently in draft status.

===== Versions

https://docs.ogc.org/DRAFTS/20-004.html[OGC API Records Part 1 Core - 20-004] is currently in draft status.

===== Implementations

The implementation of the OGC API Records is not part of the OGC Compliance Database yet.
 
===== Endpoints on the NGDI-20-60 OGC API Testbed Platform

Examples of implementations can be found on the https://ogc.heig-vd.ch/#ogc-api-features[NGDI-20-60 OGC API Testbed Platform]

=== Operations, Ressources

.Overview of OGC API Records resources, applicable HTTP methods
[cols="32,25,10",options="header"]
!===
|Resource |Path |HTTP method 
|Landing page |`/` |GET
|Conformance declaration |`/conformance` |GET 
|Records collections |`/collections` |GET 
|Records collection |`/collections/{collectionId}` |GET 
|Records |`/collections/{collectionId}/items` |GET 
|Records |`/collections/{collectionId}/items/{featureId}` 
!===

==== Relation to other OGC Standards

- <<Catalog Services for the web (CSW)>>
- <<Spatio Temporal Asset Catalog>>

==== Relation with eCH-0056

The OGC API - Records standard is not mentioned in the eCH-0056 document.

==== Proposed modifications to eCH-0056

As this is not yet an OGC standard, we cannot make any recommendations for the eCH-0056 document.

=== Spatio Temporal Asset Catalog

==== Introduction

The Spatio Temporal Asset Catalog (STAC) specification is a common language to describe geospatial information, so it can more easily be worked with, indexed, and discovered.
At its core, the SpatioTemporal Asset Catalog (STAC) specification provides a common structure for describing and cataloging spatiotemporal assets.

===== Implementations

The implementation of STAC is not part of the OGC Compliance Database yet.

===== Endpoints on the NGDI-20-60 OGC API Testbed Platform

Examples of implementations can be found on the https://ogc.heig-vd.ch/#stac-spatiotemporal-asset-catalogs[NGDI-20-60 OGC API Testbed Platform]

=== Operations, Ressources

The STAC Specification consists of 4 semi-independent specifications. Each can be used alone, but they work best in concert with one another.

* **STAC Item** is the core atomic unit, representing a single spatiotemporal asset as a GeoJSON feature plus datetime and links.

* **STAC Catalog** is a simple, flexible JSON file of links that provides a structure to organize and browse STAC Items. A series of best practices helps make recommendations for creating real world STAC Catalogs.

* **STAC Collection** is an extension of the STAC Catalog with additional information such as the extents, license, keywords, providers, etc that describe STAC Items that fall within the Collection.

* **STAC API** provides a RESTful endpoint that enables search of STAC Items, specified in OpenAPI, following OGC's WFS 3.

Source : https://stacspec.org/en

==== Relation to other OGC Standards

- <<Catalog Services for the web (CSW)>>
- <<OGC API - Records>>

==== Relation with eCH-0056

STAC is not mentioned in the eCH-0056 document.

==== Proposed modifications to eCH-0056

It is suggested to integrate STAC into the eCH-0056 document to replace AtomFeeds.
