// Document settings
[.text-justify]

== Conclusion

The standardization process is still in heavy activity to progress on the OGC API standards, with pieces approved step by step. Also we see many software implementing these pieces. Sometimes it is even by supporting the standardization work at the heart as a kind of continuous proof of concept. The https://www.osgeo.org/[OSGeo] communiy is particularly active in this field, being it in C/C++, Java or Python.

Considering the utilization of the well-established OGC WxS-standard series, the new OGC standards represent a major step towards interoperability. An example of applications that clearly benefits from this process are hybrid applications that utilize both non-spatial data and spatial data: if yesterday developers had to implement specific service interfaces for spatial data and for non-spatial data for one application, this is more and more simplified thanks to a common architectural style and geostandards. For the latter, we may also notice the general will to keep specifications modular and extensible including a conceptual level and accepting various flavors of formats.

In the past, Switzerland already played an important role in the establishment of geospatial standards due to the federal organization of the country. In the early 1990 the INTERLIS :cite[eCH-0031] standard has been created, the use of which is today required by the law for specific fields (e.g. cadastral data and minimal geodata models that define how different entities exchange data for specific themes). The Swiss Government has invested many resources to build interfaces that allow for a compatibility between the national standards and the international standards (e.g. the eCH-0018 standard :cite[ech-0118] which specifies an interface between the INTERLIS standard and the OGC Geographic Markup Language standard). Due to the regular establishment of new international standards such as the OGC API family, these interfaces need to be adapted.

Therefore and given the geostandards.ch strategy :cite[geostandards] - _sustainable and benefit-oriented standardisation in the field of geoinformation in Switzerland as well as the effective steering of the development of solutions and software tools in the environment of GeoIG and the National Spatial Data Infrastructure (NSDI)_ - the Testbed Platform described in this article should be helpful, from the tactical level to the operational level. As such, the Testbed approach is intended to live on through successive iterations.