== Work Package 3 (WP3)

The Work Package 3 (named hereafter WP3) has the intent to evaluate the current OGC standards related to vector data.

Namely, we'll investigate the:

* link:<OGC-API_Features>[OGC-API Features]
* link:<OGC-API_Styles>[OGC-API Styles]
* link:<OGC-API_Maps>[OGC-API Maps]
* link:<OGC-API_Tiles>[OGC-API Tiles]
* link:<OGC-API_Records>[OGC-API Records]

==== OGC-API Features

[quote, https://ogcapi.ogc.org/features/]
____
OGC API - Features is a multi-part standard that offers the capability to create, modify, and query spatial data on the Web and specifies requirements and recommendations for APIs that want to follow a standard way of sharing feature data.
____

==== OGC-API Styles

[quote, https://ogcapi.ogc.org/styles/]
____
The OGC API - Styles draft specification defines a Web API that enables map servers, clients as well as visual style editors, to manage and fetch styles that consist of symbolizing instructions that can be applied by a rendering engine on features and/or coverages.
____

Relation to other OGC Standards: https://docs.ogc.org/is/18-067r3/18-067r3.html[OGC Symbology Conceptual Model]

NOTE: Write a section about SymCore

==== OGC-API Maps

[quote, https://ogcapi.ogc.org/maps/]
____
The OGC API - Maps draft specification describes an API that can serve spatially referenced and dynamically rendered electronic maps. The specification describes the discovery and query operations of an API that provides access to electronic maps in a manner independent of the underlying data store. The query operations allow dynamically rendered maps to be retrieved from the underlying data store based upon simple selection criteria, defined by the client.
____

==== OGC-API Tiles

[quote, https://ogcapi.ogc.org/tiles/]
____
The OGC API - Tiles draft specification describes an API building block that can enable other OGC API implementations to serve maps or tiled feature data divided into individual tiles. The draft specification includes concepts such as tile matrix sets and tile schemes, although such concepts have been revised to allow for tiling other types of resources, such as vector tiles and not only maps. The OGC API - Tiles draft specification references the OGC Two Dimensional Tile Matrix Set (TMS) standard. The TMS standard defines the rules and requirements for a tile matrix set as a way to index space based on a set of regular grids defining a domain (tile matrix) for a limited list of scales in a Coordinate Reference System (CRS).
____

==== OGC-API Records

[quote, https://ogcapi.ogc.org/records/]

____
OGC API - Records is a multi-part draft specification that offers the capability to create, modify, and query metadata on the Web. The draft specification enables the discovery of geospatial resources by standardizing the way collections of descriptive information about the resources (metadata) are exposed. The draft specification also enables the discovery and sharing of related resources that may be referenced from geospatial resources or their metadata by standardizing the way all kinds of records are exposed and managed.
____

