name: asciidoctor-ghpages

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [bibtex]
  pull_request:
    branches: [bibtex]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Ruby setup
        uses: ruby/setup-ruby@477b21f02be01bcb8030d50f37cfec92bfa615b6
        with:
          ruby-version: 2.6
      - name: Dependencies
        run: |
          gem install asciidoctor-bibtex
      # Includes the AsciiDoctor GitHub Pages Action to convert adoc files to html and publish to gh-pages branch
      - name: Asciidoctor GitHub Pages
        uses: manoelcampos/asciidoctor-ghpages-action@v2.2.3
        with:
          pdf_build: true
          slides_build: true
          post_build: asciidoctor -r asciidoctor-bibtex README.adoc
